### PR TITLE
fix the alignment problem

### PR DESCRIPTION
**Pull request by liuheng92**
hi

sorry for my mistake.

I've pull your latest code, and added my code in it. I fix the alignment problem.

hope you can take them, thx

### CODE REVIEW

**Comment by liuheng92** [comment]
added more tags for code error return, modified parseFrom, parseFromEXIFSegment, parseFromXMPSegment functions for returning more informations

**Comment by liuheng92** [comment]
so，I've passed the request? but how can I merge it? this is my first pull request, I think I am not familiar with the process

**Comment by cdcseacave** [comment]
why is `#include <cfloat>` needed?

**Comment by liuheng92** [comment]
My Xcode build error, if not include <cfloat>.  xcode can’t recognise DBL_MAX.

**Comment by cdcseacave** [comment]
thx for these suggestions, all incorporated in 4c2f68e

**Comment by pmoulon** [comment]
Note: Ideally the best is not to use DBL_MAX and use `#include<limits>;` and `std::numeric_limits<double>::max();`

PR should be merged instead of copied paste since @cdcseacave take the ownership of the modification made be @liuheng92

**Comment by cdcseacave** [comment]
Thx for the tip Pierre, but unfortunately I was not able to copy&paste not even a line. I implemented a way to know the status of the data per EXIF/XMP that he needed, but totally different. When you have time pls check the code.

**Comment by pmoulon** [comment]
Sorry for the mix-up.

**Comment by liuheng92** [comment]
awesome

**Comment by liuheng92** [comment]
I've read your code. But I don't think it can differentiate which information was found , XMP or EXIF.

**Comment by liuheng92** [comment]
Differentiate XMP or EXIF, that's my opnions @cdcseacave. @pmoulon thanks for saying that.cdcseacave really didn't do copy&paste. And I don't care if I was the owner. The code or the idea can help others, I think it's cool. thanks @cdcseacave  take part of them. and thanks for your share again.

**Comment by liuheng92** [comment]
@pmoulon good tip for using std::numeric_limits<double>::max(); ,thx

**Comment by cdcseacave** [comment]
In order to differentiate between XMP or EXIF, pls use the Fields member which stores which of them was found in the image file.

**Pull request closed without merging**
